server {
  listen localhost:8080;
  server_name localhost;
  error_page CODE URL;
  error_page CODE URL;
  client_max_body_size 1024;

  location / {
    root PATH;
    index INDEX;
    autoindex on;
    cgi PATH FILE_ENDING;
  }

  location /test {
    root PATH;
    index INDEX;
    autoindex on;
    cgi PATH FILE_ENDING;
  }
}