server {
  listen localhost:8080;
  server_name localhost;
  error_page CODE URL;
  client_max_body_size SIZE;

  location / {
    root PATH;
    index INDEX;
    autoindex on;
    cgi_executable PATH FILE_ENDING;
  }
}

server {
  listen localhost:8080;
  server_name notexisting.com;
  error_page CODE URL;
  client_max_body_size SIZE;

  location / {
    root PATH;
    index INDEX;
    autoindex on;
    cgi_executable PATH FILE_ENDING;
  }
}

server {
  listen localhost:8081;
  server_name localhost;
  error_page CODE URL;
  client_max_body_size SIZE;

  location / {
    root PATH;
    index INDEX;
    autoindex on;
    cgi_executable PATH FILE_ENDING;
  }
}