server {
  listen 80;
  client_max_body_size 1048576;
  server_name rburgsta.example;
  
  location / {
    root /Users/rburgsta/Documents/42_webserv/website;
    methods GET;
    index index.html;
    autoindex on;
    cgi .php /notexisting;
  }

  location /redirection {
    methods GET POST DELETE;
    redirect /images/mushroom_set.png;
  }
}
