

server {
  
  
  
  listen            localhost:8080;
  server_name server1 serverTest;




  error_page                CODE URL;
  error_page CODE2 URL2; client_max_body_size         1048576;
  
  location / {
    root PATH;
    methods GET POST;
    index INDEX;
    autoindex on;
    cgi PATH FILE_ENDING;
    cgi PATH2 FILE_ENDING2;
  }

  location /test {
    root PATH2;
    methods GET POST;
    index INDEX2;
    autoindex off;
    cgi PATH FILE_ENDING;
  }

  error_page CODE4 URL3;
}



