server {
  listen localhost:80;
  client_max_body_size 1048576;
  server_name rburgsta.example;
  
  location / {
    root /home/pythongermany/_Projects/42_webserv/website;
    methods GET POST DELETE;
    index index.html;
    autoindex off;
  }

  location /redirection {
    methods GET POST DELETE;
    redirect /images/mushroom_set.png;
  }
}

server {
  listen localhost:8080;
  client_max_body_size 1048576;
  server_name rburgsta.42.fr;
  
  location / {
    root /home/pythongermany/_Projects/42_webserv/website/images/;
    methods GET POST DELETE;
    index banner.png;
    autoindex off;
  }
}

server {
  listen localhost:8080;
  client_max_body_size 1048576;
  
  location / {
    root /home/pythongermany/_Projects/42_webserv/website/images/;
    methods GET POST DELETE;
   index mushroom_set.png;
    autoindex off;
  }
}


server {
  listen localhost:8081;
  client_max_body_size 1048576;
  server_name rburgsta.42.fr;
  
  location / {
    root /home/pythongermany/_Projects/42_webserv/website/images/;
    methods GET POST DELETE;
   index banner.png;
    autoindex off;
  }
}

server {
  listen localhost:8081;
  client_max_body_size 1048576;
  
  location / {
    root /home/pythongermany/_Projects/42_webserv/website/images/;
    methods GET POST DELETE;
   index mushroom_set.png;
    autoindex off;
  }
}

server {
  listen localhost:8080;
  client_max_body_size 1048576;
  
  location / {
    root /home/pythongermany/_Projects/42_webserv/website/images/;
    methods GET POST DELETE;
   index mushroom_set.png;
    autoindex off;
  }
}