http {
  # Mime type config
  include /home/pythongermany/_Projects/42_webserv/conf/mime.types;

  # Logging config
  log_level DEBUG;
  access_log /home/pythongermany/_Projects/42_webserv/logs/access.log;
  error_log /home/pythongermany/_Projects/42_webserv/logs/error.log;

  # Virtual hosts config
  include /home/pythongermany/_Projects/42_webserv/conf/sites-enabled/*;
}