services:
  webserv:
    container_name: webserv
    build:
      context: ./webserv
    restart: unless-stopped
    environment:
      WEBSERV_ARGS: ${WEBSERV_ARGS}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
    volumes:
      - ../:/webserv
    ports:
      - 4242:4242
      - 8079:8079
      - 8080:8080
      - 8081:8081
      - 8082:8082
    depends_on:
      - mariadb
    networks:
      - docker-network

  mariadb:
    image: mariadb:latest
    container_name: ${MYSQL_HOST}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
