name: Webserv build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build binary
      uses: actions/checkout@v4
      run: make
    
    - name: Upload binary to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webserv-binary
        path: bin/webserv
        if-no-files-found: error