name: Linux build

on:
  push:
    branches:
      - main
    paths:
      - Makefile
      - include/**
      - src/**
  pull_request:
    branches:
      - main
    paths:
      - Makefile
      - include/**
      - src/**

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache object files
      id: cache-obj-files
      uses: actions/cache@v4
      with:
        path: obj
        key: ${{ runner.os }}-obj-files
    
    - name: Build binary
      run: make
    
    - name: Upload binary to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webserv-linux
        path: bin/webserv
        if-no-files-found: error
