name: Linux build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build binary
      run: make
    
    - name: Upload binary to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webserv-linux
        path: bin/webserv
        if-no-files-found: error