name: macos

on:
  push:
    branches:
      - helloworld2

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache Google Test directory
      uses: actions/cache@v3
      with:
        path: tests/googletest/
        key: googletest-${{ runner.os }}

    - name: Build with Make
      run: make test -C tests
    - name: TEST
      run: make -C tests
