name: Build with Make

on:
  push:
    branches:
      - helloworld2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Build with Make
      run: |
        git submodule update --init
        cd ${{ github.workspace }}/tests
        make
