name: Build with Make

on:
  push:
    branches:
      - helloworld2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: |
        git config --global user.name "YourUsername"
        git config --global user.email "youremail@example.com"
        git clone -b helloworld2 --recurse-submodules https://PythonGermany:${{ secrets.ACTIONS }}@github.com/PythonGermany/42_webserv.git
        cd 42_webserv/tests

    - name: Build with Make
      run: make
