name: Build with Make

on:
  push:
    branches:
      - helloworld2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Build with Make
      run: |
        cd ${{ github.workspace }}/tests
        make
