name: test
run-name: ${{ github.actor }} is testing GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: apt-get update && apt-get install -y clang make
      - name: Make and run webserv
        run: make && ./webserv conf/webserv.conf