name: linux

on:
  push:
    branches:
      - helloworld2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache Google Test directory
      uses: actions/cache@v2
      with:
        path: tests/googletest/

    - name: Build with Make
      run: make test -C ${{ github.workspace }}/tests
    - name: TEST
      run: pwd && make -C ${{ github.workspace }}/tests
